# Site settings
title: Okafor Ikenna
twitter_username: _alphaspy
name: Okafor Ikenna

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Fiverr
   url: http://fiverr.com/lemcagurl
 - title: GitHub
   url: https://github.com/bot101
 - title: StackOverflow
   url: http://stackoverflow.com/users/4687451/ikenna-anthony-okafor
 - title: Bitbucket
   url: https://bitbucket.org/bot101/
 - title: LinkedIn
   url: https://ng.linkedin.com/in/ianthony3

#Any buzzword skills you want to include
skills:
 - HTML
 - CSS
 - Javascript
 - PHP
 - MySQL
 - AngularJS
 - Ionic
 - Laravel
 - Git
 - Java
 - Cordova
 - Chrome/Firefox Extensions Development
 - Wordpress Theming & Plugin Development

#Work experience is required
roles:
 - title: Freelance Web/Mobile Application Developer
   start: 2015
   end: Ongoing
   employer: Self
   description: My responsibilities include sourcing for job descriptions that match my skill set, proposing solutions that best suit the job description and are affordable, and finally developing a solution that meets the client's needs. 

#Education is required
education:
 - level: Bachelor of Engineering (B.Eng.)
   date: 2017 (In view)
   subject: Computer & Electronics Engineering
   school: Enugu State University of Science & Technology

#This section is optional (as is the image link below)
Udacity:
   profileurl: https://https://classroom.udacity.com/me
   courses:
    - title: Mobile Web Development
      link: https://classroom.udacity.com/courses/cs256
      date: August, 2015
    - title: UX Design for Mobile Developers
      link: https://classroom.udacity.com/courses/ud849
      date: October, 2015

#List of interesting Github repo/projects to include - optional
github:
 - bot101/cordova-plugin-dbcopy
 - bot101/Instagram-API
 - bot101/Chat-API
 - bot101/GETMP3Video
 - bot101/YoutubeDownloader
 - bot101/rustless
 - bot101/cordova-plugin-background-task
 - bot101/Instagram-API

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/4687451/ikenna-anthony-okafor
   flairimageurl: http://stackoverflow.com/users/flair/4687451.png

